export interface Service {
  key: string;
  type: string;
  subtype: string;
  status: string;
  body: string;
  responser: string;
  requester: string;
  followup: string;
  requestorName: string;
  requestorPhone: string;
  province: string;
  when: string;
  seller: string;
  vehicleModel: string;
  csStatus: string;
  timeRequest: number;
  timeResponse: number;
  timeReceive: number;
  timeRead: number;
  timeEstimate: number;
  timePhone: number;
  timeSMS: number;
  dateFirstCall: number;
  payback: number;
  deleted: boolean;
  discounts: any;
  data: any;
}
